## Train Test Split

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [3]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

In [5]:
train_test_split(a)

[array([21, 32, 47, 33, 69, 12,  4,  3, 66, 93,  2, 54, 20, 97, 42, 76, 96,
        68, 11,  6, 28, 90, 95, 16, 89, 29, 77, 73, 41, 55, 58, 64, 22, 71,
        44, 17, 14, 84, 45, 53,  1, 23,  9, 82, 43, 18, 85, 59, 27, 13, 63,
        98, 26, 78, 94,  8, 37, 75, 38, 79, 86, 24, 88,  7, 60, 36, 87, 39,
        99, 67, 46, 65, 81, 25, 83]),
 array([ 50,  19,  35,  91,  80,  15,  57,  56,  34,  61,  49, 100,  52,
         51,  74,   5,  72,  30,  40,  31,  48,  10,  70,  62,  92])]

In [6]:
a_train, a_test = train_test_split(a)

In [7]:
a_train.shape, a_test.shape

((75,), (25,))

In [8]:
a_train

array([31, 80, 85, 91, 72, 16, 84, 74, 20, 61, 71, 29, 30, 78,  4, 67, 66,
       97, 35, 92, 59, 56, 39, 32, 18, 53, 64,  9, 86, 33, 89, 76, 12,  2,
       98, 50, 79,  6, 69, 58, 62, 82, 34, 93, 81, 90, 51,  7, 94,  3, 19,
       37, 27, 77, 24, 47, 38, 75, 95, 87, 52, 40, 83, 55, 10,  5, 65, 36,
       70, 42, 99, 44, 21, 68, 73])

In [9]:
a_test

array([ 11,  46,  88,   8,  22,  49, 100,  48,  14,  96,  57,  43,  23,
        41,  25,  28,  45,  54,  13,  26,  15,  60,  17,   1,  63])

In [10]:
a_train, a_test = train_test_split(a, test_size = 0.2)

In [13]:
a_train.shape, a_test.shape

((80,), (20,))

In [14]:
a_train, a_test = train_test_split(a, test_size = 0.2, shuffle=False)

In [15]:
a_train.shape, a_test.shape

((80,), (20,))

In [16]:
a_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [17]:
a_test

array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100])

In [21]:
a_train, a_test = train_test_split(a, test_size = 0.2, random_state = 42)

In [22]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [23]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

In [24]:
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size = 0.2, random_state = 42)

In [26]:
b_train.shape, b_test.shape

((80,), (20,))

In [27]:
b_train

array([556, 589, 527, 543, 570, 516, 541, 597, 510, 573, 512, 548, 586,
       529, 594, 506, 567, 566, 536, 517, 550, 535, 508, 596, 528, 520,
       582, 526, 563, 514, 525, 504, 518, 539, 509, 579, 507, 565, 537,
       590, 557, 600, 555, 544, 551, 568, 547, 569, 562, 598, 580, 542,
       559, 549, 599, 558, 576, 533, 595, 560, 564, 585, 538, 530, 502,
       553, 522, 503, 524, 588, 592, 575, 587, 583, 521, 561, 572, 515,
       593, 552])

In [28]:
b_test

array([584, 554, 571, 546, 545, 540, 523, 581, 511, 501, 519, 531, 574,
       534, 591, 505, 577, 578, 513, 532])

In [29]:
# when added a new array/matrix into train_test_split() the matching numbers still match while being randomized.